rm -Rf ACE.Adapter/bin
rm -Rf ACE.Adapter/obj
rm -Rf ACE.Common/bin
rm -Rf ACE.Common/obj
rm -Rf ACE.Database/bin
rm -Rf ACE.Database/obj
rm -Rf ACE.Database.Tests/bin
rm -Rf ACE.Database.Tests/obj
rm -Rf ACE.DatLoader/bin
rm -Rf ACE.DatLoader/obj
rm -Rf ACE.DatLoader.Tests/bin
rm -Rf ACE.DatLoader.Tests/obj
rm -Rf ACE.Entity/bin
rm -Rf ACE.Entity/obj
rm -Rf ACE.Server/bin
rm -Rf ACE.Server/obj
rm -Rf ACE.Server.Tests/bin
rm -Rf ACE.Server.Tests/obj
